# Generated by Django 4.0.2 on 2022-02-06 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the peak.', max_length=255)),
                ('altitude', models.PositiveSmallIntegerField(help_text='Altitude, in meters', validators=[django.core.validators.MaxValueValidator(5000, 'Are you sure this peak is located in Earth ?')])),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
